### ISSUE TITLE
npm run init 报错

### ISSUE THREAD

**Issue by Racaly** [iview/iview-project#1]
ERROR in ./src/main.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/**/project"
    at /home/**/project/iview-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/**/project/iview-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/home/**/project/iview-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/home/**/project/iview-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/home/**/project/iview-project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/**/project/iview-project/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/**/project/iview-project/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/**/project/iview-project/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/**/project/iview-project/node_modules/babel-loader/lib/index.js:41:20)
    at Object.module.exports (/home/**/project/iview-project/node_modules/babel-loader/lib/index.js:138:12)

**Comment by liyuzhi** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.9
3 info using node@v6.2.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle iview-project@1.0.2~predev: iview-project@1.0.2
6 silly lifecycle iview-project@1.0.2~predev: no script for predev, continuing
7 info lifecycle iview-project@1.0.2~dev: iview-project@1.0.2
8 verbose lifecycle iview-project@1.0.2~dev: unsafe-perm in lifecycle true
9 verbose lifecycle iview-project@1.0.2~dev: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\www\iview-project\node_modules\.bin;C:\Program Files (x86)\Common Files\NetSarang;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;D:\Program Files\nodejs\;C:\Program Files\Java\jdk1.7.0_60\bin; ;C:\Program Files (x86)\OpenVPN\bin;C:\Users\Administrator\AppData\Roaming\npm
10 verbose lifecycle iview-project@1.0.2~dev: CWD: D:\www\iview-project
11 silly lifecycle iview-project@1.0.2~dev: Args: [ '/d /s /c',
11 silly lifecycle   'webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js' ]
12 silly lifecycle iview-project@1.0.2~dev: Returned: code: 3221225501  signal: null
13 info lifecycle iview-project@1.0.2~dev: Failed to exec dev script
14 verbose stack Error: iview-project@1.0.2 dev: `webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js`
14 verbose stack Exit status 3221225501
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid iview-project@1.0.2
16 verbose cwd D:\www\iview-project
17 error Windows_NT 6.1.7600
18 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.2.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error iview-project@1.0.2 dev: `webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js`
22 error Exit status 3221225501
23 error Failed at the iview-project@1.0.2 dev script 'webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the iview-project package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs iview-project
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls iview-project
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by trialbox** [comment]
我在package.json 中加入
`  "babel": {
    "presets": [
      "es2015"
    ]
  }`
后能使用
