### ISSUE TITLE
nom run init 报错，采用 npm 安装。请指点！

### ISSUE THREAD

**Issue by maoycn** [iview/iview-project#19]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'init' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose run-script [ 'preinit', 'init', 'postinit' ]
5 info lifecycle iview-project@2.0.0~preinit: iview-project@2.0.0
6 silly lifecycle iview-project@2.0.0~preinit: no script for preinit, continuing
7 info lifecycle iview-project@2.0.0~init: iview-project@2.0.0
8 verbose lifecycle iview-project@2.0.0~init: unsafe-perm in lifecycle true
9 verbose lifecycle iview-project@2.0.0~init: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/maoycn/Sites/iview/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/maoycn/.mos/bin
10 verbose lifecycle iview-project@2.0.0~init: CWD: /Users/maoycn/Sites/iview
11 silly lifecycle iview-project@2.0.0~init: Args: [ '-c', 'webpack --progress --config webpack.dev.config.js' ]
12 silly lifecycle iview-project@2.0.0~init: Returned: code: 2  signal: null
13 info lifecycle iview-project@2.0.0~init: Failed to exec init script
14 verbose stack Error: iview-project@2.0.0 init: `webpack --progress --config webpack.dev.config.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid iview-project@2.0.0
16 verbose cwd /Users/maoycn/Sites/iview
17 error Darwin 16.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "init"
19 error node v7.8.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error iview-project@2.0.0 init: `webpack --progress --config webpack.dev.config.js`
23 error Exit status 2
24 error Failed at the iview-project@2.0.0 init script 'webpack --progress --config webpack.dev.config.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the iview-project package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     webpack --progress --config webpack.dev.config.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs iview-project
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls iview-project
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]

**Comment by maoycn** [comment]
index.html 文件内容：

Html Webpack Plugin:
<pre>
  Error: Child compilation failed:
  Module build failed: SyntaxError: Unexpected token (1:0)
  > 1 | <!DOCTYPE html>      | ^
    2 | <html lang="zh-CN">
    3 | <head>
    4 |     <title>iView project</[  33mtitle>
  :
  BabelLoaderError: SyntaxError: Unexpected token (1:0)
  > 1 | <!DOCTYPE html>      | ^
    2 | <html lang="zh-CN">
    3 | <head>
    4 |     <title>iView project</[  33mtitle>
  
  - compiler.js:76 
    [iview]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:296 Compiler.<anonymous>
    [iview]/[webpack]/lib/Compiler.js:296:10
  
  - Compiler.js:499 
    [iview]/[webpack]/lib/Compiler.js:499:13
  
  - Tapable.js:138 next
    [iview]/[tapable]/lib/Tapable.js:138:11
  
  - CachePlugin.js:62 Compiler.<anonymous>
    [iview]/[webpack]/lib/CachePlugin.js:62:5
  
  - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    [iview]/[tapable]/lib/Tapable.js:142:13
  
  - Compiler.js:496 
    [iview]/[webpack]/lib/Compiler.js:496:10
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [iview]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:649 self.applyPluginsAsync.err
    [iview]/[webpack]/lib/Compilation.js:649:19
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [iview]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:640 self.applyPluginsAsync.err
    [iview]/[webpack]/lib/Compilation.js:640:11
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [iview]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:635 self.applyPluginsAsync.err
    [iview]/[webpack]/lib/Compilation.js:635:10
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [iview]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:631 sealPart2
    [iview]/[webpack]/lib/Compilation.js:631:9
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [iview]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:579 Compilation.seal
    [iview]/[webpack]/lib/Compilation.js:579:8
  
  - Compiler.js:493 
    [iview]/[webpack]/lib/Compiler.js:493:16
  
  - Tapable.js:225 
    [iview]/[tapable]/lib/Tapable.js:225:11
  
  - Compilation.js:481 _addModuleChain
    [iview]/[webpack]/lib/Compilation.js:481:11
  
  - Compilation.js:452 processModuleDependencies.err
    [iview]/[webpack]/lib/Compilation.js:452:13
  
  - next_tick.js:73 _combinedTickCallback
    internal/process/next_tick.js:73:7
  
  - next_tick.js:104 process._tickCallback
    internal/process/next_tick.js:104:9
  
</pre>

**Comment by vision-yip** [comment]
解决错误两种方法:
1:webpack.base.config.js
`{
                test: /\.(html|tpl)$/,
                loader: 'html-loader'
            }`
改成
`{
                test: /\.(html|tpl|ejs)$/,
                loader: 'html-loader'
            }`
2:webpack.dev.config.js
`new HtmlWebpackPlugin({
            filename: '../index.html',
            template: './src/template/index.ejs',
            inject: false
        })`
注释template: './src/template/index.ejs',

以上两个方法中的一个,然后重新运行项目

**Comment by pineli** [comment]
Hi, I`m with same problem

````
npm run init

> iview-project@2.0.0 init /Users/pineli/Projetos/iview/iview-project
> webpack --progress --config webpack.dev.config.js

  0% compiling(node:8648) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
 10% building modules 5/9 modules 4 active ...iew/iview-project/src/views/index.vue[BABEL] Note: The code generator has deoptimised the styling of "/Users/pineli/Projetos/iview/iview-project/node_modules/iview/dist/iview.js" as it exceeds the max of "500KB".
 11% building modules 16/18 modules 2 active ...ue-loader/lib/component-normalizer.jsContainer#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Container#remove is deprecated. Use Container#removeChild
Node#_value was deprecated. Use Node#raws.value
Hash: 81ef4bb3c26afcc33fb5
Version: webpack 2.7.0
Time: 16448ms
                                Asset       Size  Chunks                    Chunk Names
                           vendors.js     913 kB       2  [emitted]  [big]  vendors
 2c2ae068be3b089e0a5b59abb1831550.eot     121 kB          [emitted]
 24712f6c47821394fba7942fbb52c3b2.ttf     189 kB          [emitted]
05acfdb568b3df49ad31355b19495d4a.woff    67.9 kB          [emitted]
 76ecb6e76d2c438065f90cd7f8fa7371.png    1.56 kB          [emitted]
                           0.chunk.js    3.04 kB       0  [emitted]
                              main.js    6.79 kB       1  [emitted]         main
 621bd386841f74e0053cb8e67f8a0604.svg     334 kB          [emitted]  [big]
                             main.css     230 kB       1  [emitted]         main
                       0.chunk.js.map    5.97 kB       0  [emitted]
                          main.js.map    7.81 kB       1  [emitted]         main
                         main.css.map   85 bytes       1  [emitted]         main
                       vendors.js.map    2.29 MB       2  [emitted]         vendors
                        ../index.html  520 bytes          [emitted]
   [0] ./~/vue/dist/vue.esm.js 263 kB {2} [built]
   [1] ./~/iview/dist/iview.js 573 kB {2} [built]
   [2] ./~/vue-router/dist/vue-router.esm.js 62.4 kB {2} [built]
   [4] ./src/libs/util.js 163 bytes {1} [built]
   [5] ./src/router.js 203 bytes {1} [built]
   [6] ./~/iview/dist/styles/iview.css 41 bytes {1} [built]
   [7] ./src/app.vue 1.68 kB {1} [built]
   [8] ./~/vue-loader/lib/component-normalizer.js 1.27 kB {1} [built]
   [9] ./src/main.js 714 bytes {1} [built]
  [10] ./src/vendors.js 85 bytes {2} [built]
  [11] ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue 199 bytes {1} [built]
  [12] (webpack)/buildin/global.js 808 bytes {2} [built]
  [13] (webpack)/buildin/module.js 506 bytes {2} [built]
  [14] ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"data-v-500777ba","scoped":true,"hasInlineConfig":false}!./~/autoprefixer-loader!./~/less-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/app.vue 41 bytes {1} [built]
  [15] ./~/vue-loader/lib/template-compiler?{"id":"data-v-500777ba"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/app.vue 381 bytes {1} [built]
    + 6 hidden modules
Child html-webpack-plugin for "../index.html":
       [0] ./~/html-webpack-plugin/lib/loader.js!./src/template/index.ejs 577 bytes {0} [built]
Child extract-text-webpack-plugin:
                                    Asset     Size  Chunks                    Chunk Names
     2c2ae068be3b089e0a5b59abb1831550.eot   121 kB          [emitted]
     621bd386841f74e0053cb8e67f8a0604.svg   334 kB          [emitted]  [big]
     24712f6c47821394fba7942fbb52c3b2.ttf   189 kB          [emitted]
    05acfdb568b3df49ad31355b19495d4a.woff  67.9 kB          [emitted]
       [0] ./~/iview/dist/styles/fonts/ionicons.eot?v=2.0.0 82 bytes {0} [built]
       [1] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
       [2] ./~/iview/dist/styles/fonts/ionicons.svg?v=2.0.0 82 bytes {0} [built]
       [3] ./~/iview/dist/styles/fonts/ionicons.ttf?v=2.0.0 82 bytes {0} [built]
       [4] ./~/iview/dist/styles/fonts/ionicons.woff?v=2.0.0 83 bytes {0} [built]
       [5] ./~/css-loader?minimize!./~/autoprefixer-loader!./~/iview/dist/styles/iview.css 232 kB {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
       [1] ./~/css-loader?minimize!./~/vue-loader/lib/style-compiler?{"id":"data-v-78d3d5f3","scoped":true,"hasInlineConfig":false}!./~/autoprefixer-loader!./~/less-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/views/index.vue 486 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
       [1] ./~/css-loader!./src/styles/common.css 157 bytes {0} [built]
       [2] ./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"data-v-500777ba","scoped":true,"hasInlineConfig":false}!./~/autoprefixer-loader!./~/less-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/app.vue 240 bytes {0} [built]
```


```
npm run dev

> iview-project@2.0.0 dev /Users/pineli/Projetos/iview/iview-project
> webpack-dev-server --content-base ./ --open --inline --hot --compress --history-api-fallback --config webpack.dev.config.js

(node:8681) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Project is running at http://localhost:8080/
webpack output is served from /dist/
Content not from webpack is served from /Users/pineli/Projetos/iview/iview-project
404s will fallback to /index.html
URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.files.css[0]%20%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:317:13)
    at /Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:317:13)
    at /Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.files.js[0]%20%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:317:13)
    at /Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:317:13)
    at /Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.files.js[1]%20%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:317:13)
    at /Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:317:13)
    at /Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/pineli/Projetos/iview/iview-project/node_modules/express/lib/router/index.js:335:12)
[BABEL] Note: The code generator has deoptimised the styling of "/Users/pineli/Projetos/iview/iview-project/node_modules/iview/dist/iview.js" as it exceeds the max of "500KB".
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Container#remove is deprecated. Use Container#removeChild
Node#_value was deprecated. Use Node#raws.value
Hash: 6d47643cebc70518a494
Version: webpack 2.7.0
Time: 20645ms
                                Asset       Size  Chunks                    Chunk Names
                           vendors.js    1.26 MB       2  [emitted]  [big]  vendors
 2c2ae068be3b089e0a5b59abb1831550.eot     121 kB          [emitted]
 24712f6c47821394fba7942fbb52c3b2.ttf     189 kB          [emitted]
05acfdb568b3df49ad31355b19495d4a.woff    67.9 kB          [emitted]
 76ecb6e76d2c438065f90cd7f8fa7371.png    1.56 kB          [emitted]
                           0.chunk.js       3 kB       0  [emitted]
                              main.js    10.6 kB       1  [emitted]         main
 621bd386841f74e0053cb8e67f8a0604.svg     334 kB          [emitted]  [big]
                             main.css     230 kB       1  [emitted]         main
                       0.chunk.js.map    5.98 kB       0  [emitted]
                          main.js.map    15.7 kB       1  [emitted]         main
                         main.css.map   85 bytes       1  [emitted]         main
                       vendors.js.map    2.96 MB       2  [emitted]         vendors
                        ../index.html  520 bytes          [emitted]
chunk    {0} 0.chunk.js, 0.chunk.js.map 3.09 kB {1} [rendered]
  [103] ./src/views/index.vue 1.72 kB {0} [built]
  [104] ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/index.vue 363 bytes {0} [built]
  [105] ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?minimize!./~/vue-loader/lib/style-compiler?{"id":"data-v-78d3d5f3","scoped":true,"hasInlineConfig":false}!./~/autoprefixer-loader!./~/less-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/views/index.vue 41 bytes {0} [built]
  [106] ./src/images/logo.png 82 bytes {0} [built]
  [107] ./~/vue-loader/lib/template-compiler?{"id":"data-v-78d3d5f3"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/views/index.vue 884 bytes {0} [built]
chunk    {1} main.js, main.css, main.js.map, main.css.map (main) 8.44 kB {2} [initial] [rendered]
   [24] ./~/vue-loader/~/vue-hot-reload-api/index.js 3.69 kB {1} [built]
   [43] ./src/main.js 714 bytes {1} [built]
   [45] ./~/vue-loader/lib/component-normalizer.js 1.27 kB {1} [built]
   [48] ./src/libs/util.js 163 bytes {1} [built]
   [49] ./src/router.js 203 bytes {1} [built]
   [92] ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue 199 bytes {1} [built]
   [96] ./~/iview/dist/styles/iview.css 41 bytes {1} [built]
   [97] ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"data-v-500777ba","scoped":true,"hasInlineConfig":false}!./~/autoprefixer-loader!./~/less-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/app.vue 41 bytes {1} [built]
   [98] ./src/app.vue 1.68 kB {1} [built]
   [99] ./~/vue-loader/lib/template-compiler?{"id":"data-v-500777ba"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/app.vue 381 bytes {1} [built]
  [101] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main 52 bytes {1} [built]
chunk    {2} vendors.js, vendors.js.map (vendors) 1.22 MB [entry] [rendered]
   [10] ./~/vue/dist/vue.esm.js 263 kB {2} [built]
   [16] (webpack)-dev-server/client?http://localhost:8080 5.96 kB {2} [built]
   [17] (webpack)/hot/dev-server.js 1.53 kB {2} [built]
   [26] ./~/iview/dist/iview.js 573 kB {2} [built]
   [41] ./~/vue-router/dist/vue-router.esm.js 62.4 kB {2} [built]
   [42] (webpack)/hot/emitter.js 74 bytes {2} [built]
   [44] ./src/vendors.js 85 bytes {2} [built]
   [55] ./~/loglevel/lib/loglevel.js 7.41 kB {2} [built]
   [88] ./~/strip-ansi/index.js 161 bytes {2} [built]
   [90] ./~/url/url.js 23.1 kB {2} [built]
   [93] (webpack)-dev-server/client/overlay.js 3.59 kB {2} [built]
   [94] (webpack)-dev-server/client/socket.js 857 bytes {2} [built]
   [95] (webpack)/hot/log-apply-result.js 998 bytes {2} [built]
  [100] (webpack)/hot nonrecursive ^\.\/log$ 160 bytes {2} [built]
  [102] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/vendors 52 bytes {2} [built]
     + 77 hidden modules
Child html-webpack-plugin for "../index.html":
    chunk    {0} ../index.html 577 bytes [entry] [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/template/index.ejs 577 bytes {0} [built]
Child extract-text-webpack-plugin:
                                    Asset     Size  Chunks                    Chunk Names
     2c2ae068be3b089e0a5b59abb1831550.eot   121 kB          [emitted]
     621bd386841f74e0053cb8e67f8a0604.svg   334 kB          [emitted]  [big]
     24712f6c47821394fba7942fbb52c3b2.ttf   189 kB          [emitted]
    05acfdb568b3df49ad31355b19495d4a.woff  67.9 kB          [emitted]
    chunk    {0} extract-text-webpack-plugin-output-filename 234 kB [entry] [rendered]
        [0] ./~/iview/dist/styles/fonts/ionicons.eot?v=2.0.0 82 bytes {0} [built]
        [1] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
        [2] ./~/iview/dist/styles/fonts/ionicons.svg?v=2.0.0 82 bytes {0} [built]
        [3] ./~/iview/dist/styles/fonts/ionicons.ttf?v=2.0.0 82 bytes {0} [built]
        [4] ./~/iview/dist/styles/fonts/ionicons.woff?v=2.0.0 83 bytes {0} [built]
        [5] ./~/css-loader?minimize!./~/autoprefixer-loader!./~/iview/dist/styles/iview.css 232 kB {0} [built]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 1.95 kB [entry] [rendered]
        [0] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
        [1] ./~/css-loader?minimize!./~/vue-loader/lib/style-compiler?{"id":"data-v-78d3d5f3","scoped":true,"hasInlineConfig":false}!./~/autoprefixer-loader!./~/less-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/views/index.vue 486 bytes {0} [built]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 1.86 kB [entry] [rendered]
        [0] ./~/css-loader/lib/css-base.js 1.46 kB {0} [built]
        [1] ./~/css-loader!./src/styles/common.css 157 bytes {0} [built]
        [2] ./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"data-v-500777ba","scoped":true,"hasInlineConfig":false}!./~/autoprefixer-loader!./~/less-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/app.vue 240 bytes {0} [built]
webpack: Compiled successfully.
^[[1;2B
```

**Comment by jiangbai333** [comment]
@vision-yip 
您好，按照您的方案，修改后，好使了，但是请问是如后通过上面的错误信息，确定的这样修改！
谢谢！

**Comment by vision-yip** [comment]
@jiangbai333 因为ejs文件解析不了  BabelLoaderError
