### ISSUE TITLE
npm init 出错

### ISSUE THREAD

**Issue by pidehen23** [iview/iview-project#58]
C:\Users\10517\Desktop\iview-project-3.0>npm run init

> iview-project@3.0.0 init C:\Users\10517\Desktop\iview-project-3.0
> webpack --progress --config webpack.dev.config.js

  0% compilingfs.js:133
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.write (fs.js:540:14)
    at C:\Users\10517\Desktop\iview-project-3.0\webpack.dev.config.js:10:8
    at FSReqWrap.oncomplete (fs.js:145:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iview-project@3.0.0 init: `webpack --progress --config webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iview-project@3.0.0 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\10517\AppData\Roaming\npm-cache\_logs\2018-08-19T13_33_40_191Z-debug.log

**Comment by tweikiang** [comment]
In your "webpack.dev.config.js"
replace 
`fs.write(fd, buf, 0, buf.length, 0, function (err, written, buffer){});`
with 
`fs.write(fd, buf, function(err, written, buffer) {});`

same goes to production webpack config

**Comment by tanxuxu** [comment]
npm run init
