### ISSUE TITLE
npm run init 报错

### ISSUE THREAD

**Issue by newbaner** [iview/iview-project#67]
> iview-project@3.0.0 init D:\projects\vue\iview-project
> webpack --progress --config webpack.dev.config.js

  0% compilingfs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.write (fs.js:533:14)
    at D:\projects\vue\iview-project\webpack.dev.config.js:10:8
    at FSReqWrap.oncomplete (fs.js:141:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iview-project@3.0.0 init: `webpack --progress --config webpack.dev.config.js`
npm ERR! Exit status 1

**Comment by davidmoshal** [comment]
+1 
I guess iView is abandoned?

**Comment by newbaner** [comment]
I solved it！You can try the following method：
"webpack.dev.config.js"
replace
fs.write(fd, buf, 0, buf.length, 0, function (err, written, buffer){});
with
fs.write(fd, buf, function(err, written, buffer) {});

**Comment by 1400LightYear-Pisces** [comment]
> 
> 
> I solved it！You can try the following method：
> "webpack.dev.config.js"
> replace
> fs.write(fd, buf, 0, buf.length, 0, function (err, written, buffer){});
> with
> fs.write(fd, buf, function(err, written, buffer) {});

yes,it's very useful!!
thank you.

**Comment by weberbo** [comment]
> I solved it！You can try the following method：
> "webpack.dev.config.js"
> replace
> fs.write(fd, buf, 0, buf.length, 0, function (err, written, buffer){});
> with
> fs.write(fd, buf, function(err, written, buffer) {});

Thx!

**Comment by fisher-monkey** [comment]
@newbaner 
It works, Thx!

**Comment by roronoaxyz** [comment]
it s right zeze

**Comment by ace1573** [comment]
> I solved it！You can try the following method：
> "webpack.dev.config.js"
> replace
> fs.write(fd, buf, 0, buf.length, 0, function (err, written, buffer){});
> with
> fs.write(fd, buf, function(err, written, buffer) {});

good job

**Comment by hiroban** [comment]
You also do like this:
  file: webpack.dev.config.js
    change:
      fs.write(fd, buf, 0, buf.length, 0, function(err, written, buffer) {});
    to
      fs.write(fd, buf, 0, 'utf-8', function(err, written, buffer) {});

Function  fs.write with Node v10+  callback must be.

**Comment by wsyxl365** [comment]
> I solved it！You can try the following method：
> "webpack.dev.config.js"
> replace
> fs.write(fd, buf, 0, buf.length, 0, function (err, written, buffer){});
> with
> fs.write(fd, buf, function(err, written, buffer) {});

good job man ! thanks  ~.~

**Comment by jmliu1983** [comment]
> I solved it！You can try the following method：
> "webpack.dev.config.js"
> replace
> fs.write(fd, buf, 0, buf.length, 0, function (err, written, buffer){});
> with
> fs.write(fd, buf, function(err, written, buffer) {});

Thanks~
