### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by blackcatpolice** [iview/iview-project#8]
> webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! iview-project@1.0.2 dev: `webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iview-project@1.0.2 dev script 'webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iview-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iview-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iview-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Repos\iVivew\iviewproject\npm-debug.log

**Comment by yobi-maggie** [comment]
同问   +1

**Comment by yangjh168** [comment]
端口被占用
